M48
; DRILL file {KiCad 8.0.6} date 2025-06-01T11:12:35+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-01T11:12:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.7474Y-6.6465
X3.9384Y-6.6465
T2
X3.7356Y-6.7657
X3.9502Y-6.7657
M30
