M48
; DRILL file {KiCad 8.0.6} date 2025-05-31T15:31:02+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-31T15:31:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.8394Y-3.6404
X4.8394Y-3.8313
T2
X4.7201Y-3.6285
X4.7201Y-3.8431
M30
